import React, { useState } from 'react';
import { View, Text, StyleSheet, FlatList, Image, TouchableOpacity, Modal } from 'react-native';
import { useRouter } from 'expo-router';
import { ArrowLeft, Trash2, ShoppingBag, CheckCircle2 } from 'lucide-react-native';
import { useCart } from './context/CartContext';

export default function CartScreen() {
  const router = useRouter();
    const { cart, removeFromCart, totalPrice, clearCart } = useCart();
      const [orderSuccess, setOrderSuccess] = useState(false); 

        const handleOrder = () => {
            setOrderSuccess(true);
                // كيمسح السلة ويرجع للرئيسية بعد 3 ثواني
                    setTimeout(() => {
                          clearCart();
                                setOrderSuccess(false);
                                      router.push('/');
                                          }, 3000);
                                            };

                                              return (
                                                  <View style={styles.container}>
                                                        {/* Header */}
                                                              <View style={styles.header}>
                                                                      <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
                                                                                <ArrowLeft size={24} color="#000" />
                                                                                        </TouchableOpacity>
                                                                                                <Text style={styles.headerTitle}>سلة المشتريات</Text>
                                                                                                        <View style={{ width: 45 }} />
                                                                                                              </View>

                                                                                                                    {cart.length === 0 ? (
                                                                                                                            <View style={styles.emptyContainer}>
                                                                                                                                      <ShoppingBag size={80} color="#ccc" />
                                                                                                                                                <Text style={styles.emptyText}>السلة خاوية.. جيعان؟</Text>
                                                                                                                                                          <TouchableOpacity style={styles.orderBtn} onPress={() => router.push('/')}>
                                                                                                                                                                      <Text style={styles.orderBtnText}>اكتشف المأكولات</Text>
                                                                                                                                                                                </TouchableOpacity>
                                                                                                                                                                                        </View>
                                                                                                                                                                                              ) : (
                                                                                                                                                                                                      <>
                                                                                                                                                                                                                <FlatList
                                                                                                                                                                                                                            data={cart}
                                                                                                                                                                                                                                        keyExtractor={(item) => item.id.toString()}
                                                                                                                                                                                                                                                    renderItem={({ item }) => (
                                                                                                                                                                                                                                                                  <View style={styles.cartItem}>
                                                                                                                                                                                                                                                                                  <Image source={{ uri: item.img }} style={styles.itemImg} />
                                                                                                                                                                                                                                                                                                  <View style={styles.itemInfo}>
                                                                                                                                                                                                                                                                                                                    <Text style={styles.itemName}>{item.name}</Text>
                                                                                                                                                                                                                                                                                                                                      <Text style={styles.itemPrice}>{item.price} x {item.qty || 1}</Text>
                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                      <TouchableOpacity 
                                                                                                                                                                                                                                                                                                                                                                                        style={styles.deleteBtn} 
                                                                                                                                                                                                                                                                                                                                                                                                          onPress={() => removeFromCart(item.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                            <Trash2 size={20} color="#FF5733" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  contentContainerStyle={{ padding: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <View style={styles.footer}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <View style={styles.totalRow}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={styles.totalLabel}>المجموع الإجمالي</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Text style={styles.totalValue}>{totalPrice} DH</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <TouchableOpacity style={styles.checkoutBtn} onPress={handleOrder}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.checkoutText}>تأكيد الطلب</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Success Modal - بديل الـ Popup البشع */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Modal visible={orderSuccess} transparent animationType="fade">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <View style={styles.modalOverlay}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <View style={styles.modalContent}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <View style={styles.iconCircle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <CheckCircle2 size={60} color="#fff" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text style={styles.modalTitle}>تم تأكيد طلبك!</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.modalSub}>الطلبية ديالك دابا في الطريق للمطبخ. 🚀</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={styles.modalTimer}>سوف يتم توجيهك للرئيسية...</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Modal>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                container: { flex: 1, backgroundColor: '#fff', paddingTop: 60 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backBtn: { backgroundColor: '#f5f5f5', padding: 10, borderRadius: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      headerTitle: { fontSize: 20, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingBottom: 100 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          emptyText: { fontSize: 18, color: '#999', marginTop: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            orderBtn: { marginTop: 20, backgroundColor: '#FF5733', paddingHorizontal: 30, paddingVertical: 15, borderRadius: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              orderBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cartItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fcfcfc', padding: 15, borderRadius: 25, marginBottom: 15, borderWidth: 1, borderColor: '#f0f0f0' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  itemImg: { width: 80, height: 80, borderRadius: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    itemInfo: { flex: 1, marginLeft: 15, alignItems: 'flex-start' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      itemName: { fontSize: 16, fontWeight: 'bold', color: '#333' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        itemPrice: { color: '#FF5733', marginTop: 5, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          deleteBtn: { padding: 10, backgroundColor: '#FFF0ED', borderRadius: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            footer: { padding: 30, borderTopWidth: 1, borderTopColor: '#eee', backgroundColor: '#fff' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              totalRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                totalLabel: { fontSize: 18, color: '#888' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  totalValue: { fontSize: 24, fontWeight: 'bold', color: '#000' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    checkoutBtn: { backgroundColor: '#FF5733', padding: 20, borderRadius: 22, alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      checkoutText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          modalContent: { backgroundColor: '#fff', padding: 40, borderRadius: 35, alignItems: 'center', width: '85%' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            iconCircle: { backgroundColor: '#4BB543', padding: 20, borderRadius: 100, marginBottom: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              modalTitle: { fontSize: 24, fontWeight: 'bold', color: '#333' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                modalSub: { color: '#666', marginTop: 10, textAlign: 'center', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  modalTimer: { color: '#FF5733', marginTop: 20, fontSize: 12 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });