import React, { useState, useEffect } from 'react';
import { View, Text, ScrollView, StyleSheet, TouchableOpacity, TextInput, Image, ActivityIndicator } from 'react-native';
import { ShoppingCart, Search, MapPin, Star } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { useCart } from '../context/CartContext';
import * as Location from 'expo-location';

const DATA = [
  { id: '1', name: 'كلاسيك تشيز برغر', price: '45 DH', rating: '4.8', time: '20-30 min', img: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=500' },
    { id: '2', name: 'بيتزا إيطالية', price: '55 DH', rating: '4.5', time: '25-35 min', img: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=500' },
      { id: '3', name: 'تاكوس ميكس', price: '35 DH', rating: '4.2', time: '15-20 min', img: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=500' },
        { id: '4', name: 'سلطة سيزر', price: '25 DH', rating: '4.9', time: '10-15 min', img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=500' },
        ];

        export default function HomeScreen() {
          const router = useRouter();
            const { cartCount } = useCart();
              const [activeCat, setActiveCat] = useState('الكل');
                const [locationName, setLocationName] = useState('كاري الموقع...');
                  const [loading, setLoading] = useState(true);

                    useEffect(() => {
                        (async () => {
                              const { status: fore } = await Location.requestForegroundPermissionsAsync();
                                    const { status: back } = await Location.requestBackgroundPermissionsAsync();
                                          
                                                if (fore === 'granted') {
                                                        try {
                                                                  const currentPos = await Location.getCurrentPositionAsync({});
                                                                            const address = await Location.reverseGeocodeAsync(currentPos.coords);
                                                                                      if (address && address[0]) {
                                                                                                  // غيطلع ليك "تيفلت" أو "Tiflet" أوتوماتيكياً حسب فين نتا دابا
                                                                                                              setLocationName(`${address[0].city || address[0].region}, المغرب`);
                                                                                                                        }
                                                                                                                                } catch (err) {
                                                                                                                                          setLocationName("موقع غير معروف");
                                                                                                                                                  }
                                                                                                                                                        }

                                                                                                                                                              if (fore === 'granted' && back === 'granted') {
                                                                                                                                                                      try {
                                                                                                                                                                                await Location.startGeofencingAsync('MOBILE_ORDER_GEOFENCE', [
                                                                                                                                                                                            {
                                                                                                                                                                                                          identifier: 'CURRENT_ZONE',
                                                                                                                                                                                                                        latitude: 33.8938, // إحداثيات تيفلت
                                                                                                                                                                                                                                      longitude: -6.3131,
                                                                                                                                                                                                                                                    radius: 300,
                                                                                                                                                                                                                                                                  notifyOnEnter: true,
                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                        ]);
                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                          console.log("Geofencing error:", e);
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                                                                                                                                                                  })();
                                                                                                                                                                                                                                                                                                                                    }, []);

                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                          <View style={styles.container}>
                                                                                                                                                                                                                                                                                                                                                <View style={styles.header}>
                                                                                                                                                                                                                                                                                                                                                        <View>
                                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.subTitle}>توصيل إلى</Text>
                                                                                                                                                                                                                                                                                                                                                                            <View style={styles.locationRow}>
                                                                                                                                                                                                                                                                                                                                                                                        <MapPin size={16} color="#FF5733" />
                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.locationText}>{locationName}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                              </View>
                                                                                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                                                                              <TouchableOpacity style={styles.cartBtn} onPress={() => router.push("/cart")}>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <ShoppingCart size={22} color="#333" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {cartCount > 0 && <View style={styles.badge}><Text style={styles.badgeText}>{cartCount}</Text></View>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </View>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ScrollView showsVerticalScrollIndicator={false}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <View style={styles.searchSection}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <View style={styles.searchBar}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Search size={20} color="#999" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TextInput placeholder="شنو بغيتي تاكل اليوم؟" style={styles.searchInput} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </View>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.catScroll} contentContainerStyle={{ paddingLeft: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {['الكل', '🍔 برغر', '🍕 بيتزا', '🌮 تاكوس', '🥗 سلطة'].map((cat, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TouchableOpacity key={i} onPress={() => setActiveCat(cat)} style={[styles.catItem, activeCat === cat && styles.catActive]}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Text style={[styles.catText, activeCat === cat && styles.catTextActive]}>{cat}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ScrollView>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <View style={styles.section}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Text style={styles.sectionTitle}>الأكثر مبيعاً 🔥</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ActivityIndicator size="large" color="#FF5733" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <View style={styles.grid}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {DATA.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <TouchableOpacity key={item.id} style={styles.card} onPress={() => router.push({ pathname: "/product-details", params: item })}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Image source={{ uri: item.img }} style={styles.cardImg} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <View style={styles.cardInfo}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={styles.foodName}>{item.name}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <View style={styles.meta}><Star size={12} color="#FFD700" /><Text style={styles.metaText}>{item.rating} • {item.time}</Text></View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text style={styles.price}>{item.price}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    container: { flex: 1, backgroundColor: '#fcfcfc', paddingTop: 50 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      header: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 20, alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        subTitle: { color: '#888', fontSize: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          locationRow: { flexDirection: 'row', alignItems: 'center', marginTop: 2 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            locationText: { fontSize: 15, fontWeight: 'bold', marginLeft: 4, color: '#333' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cartBtn: { backgroundColor: '#fff', padding: 10, borderRadius: 15, elevation: 3 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                badge: { position: 'absolute', top: -5, right: -5, backgroundColor: '#FF5733', width: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  badgeText: { color: '#fff', fontSize: 10, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    searchSection: { paddingHorizontal: 20, marginTop: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      searchBar: { backgroundColor: '#f2f2f2', flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        searchInput: { flex: 1, marginLeft: 10, textAlign: 'right' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          catScroll: { marginVertical: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            catItem: { paddingHorizontal: 20, paddingVertical: 10, backgroundColor: '#f0f0f0', borderRadius: 12, marginRight: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              catActive: { backgroundColor: '#FF5733' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                catText: { fontWeight: 'bold', color: '#666' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  catTextActive: { color: '#fff' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    section: { paddingHorizontal: 20, paddingBottom: 100 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sectionTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          card: { backgroundColor: '#fff', width: '48%', borderRadius: 25, marginBottom: 15, elevation: 4, overflow: 'hidden' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cardImg: { width: '100%', height: 120 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cardInfo: { padding: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                foodName: { fontSize: 14, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  meta: { flexDirection: 'row', alignItems: 'center', gap: 5, marginVertical: 5 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    metaText: { fontSize: 10, color: '#888' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      price: { color: '#FF5733', fontWeight: 'bold', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });